/********************************************
* file generated by the script ./mapping
* mapping.h
*
* @author Felix Touchte Codjo
* @date April 22, 2025  22:17:46
* *******************************************/


#ifndef AHDC_MAPPING_H
#define AHDC_MAPPING_H

class AhdcMapping {
public :
        static void GetDreamChannel(int sector, int layer, int component, int &crate, int & slot, int & channel);
};

#endif
