/********************************************
* file generated by the script ./mapping
* mapping.cpp
*
* @author Felix Touchte Codjo
* @date May 26, 2025  08:00:37
* *******************************************/


#include "AhdcMapping.h"



void AhdcMapping::GetDreamChannel(int sector, int layer, int component, int &crate, int & slot, int & channel) {
        if ((sector == 1) && (layer == 51) && (component == 47)) {
                crate   = 79;
                slot    = 1;
                channel = 65;
        }
        else if ((sector == 1) && (layer == 51) && (component == 44)) {
                crate   = 79;
                slot    = 1;
                channel = 66;
        }
        else if ((sector == 1) && (layer == 51) && (component == 48)) {
                crate   = 79;
                slot    = 1;
                channel = 67;
        }
        else if ((sector == 1) && (layer == 51) && (component == 45)) {
                crate   = 79;
                slot    = 1;
                channel = 68;
        }
        else if ((sector == 1) && (layer == 51) && (component == 49)) {
                crate   = 79;
                slot    = 1;
                channel = 69;
        }
        else if ((sector == 1) && (layer == 51) && (component == 46)) {
                crate   = 79;
                slot    = 1;
                channel = 70;
        }
        else if ((sector == 1) && (layer == 42) && (component == 43)) {
                crate   = 79;
                slot    = 1;
                channel = 71;
        }
        else if ((sector == 1) && (layer == 42) && (component == 40)) {
                crate   = 79;
                slot    = 1;
                channel = 72;
        }
        else if ((sector == 1) && (layer == 41) && (component == 41)) {
                crate   = 79;
                slot    = 1;
                channel = 73;
        }
        else if ((sector == 1) && (layer == 42) && (component == 41)) {
                crate   = 79;
                slot    = 1;
                channel = 74;
        }
        else if ((sector == 1) && (layer == 41) && (component == 42)) {
                crate   = 79;
                slot    = 1;
                channel = 75;
        }
        else if ((sector == 1) && (layer == 42) && (component == 42)) {
                crate   = 79;
                slot    = 1;
                channel = 76;
        }
        else if ((sector == 1) && (layer == 41) && (component == 43)) {
                crate   = 79;
                slot    = 1;
                channel = 77;
        }
        else if ((sector == 1) && (layer == 41) && (component == 39)) {
                crate   = 79;
                slot    = 1;
                channel = 78;
        }
        else if ((sector == 1) && (layer == 32) && (component == 35)) {
                crate   = 79;
                slot    = 1;
                channel = 79;
        }
        else if ((sector == 1) && (layer == 41) && (component == 40)) {
                crate   = 79;
                slot    = 1;
                channel = 80;
        }
        else if ((sector == 1) && (layer == 32) && (component == 36)) {
                crate   = 79;
                slot    = 1;
                channel = 81;
        }
        else if ((sector == 1) && (layer == 32) && (component == 33)) {
                crate   = 79;
                slot    = 1;
                channel = 82;
        }
        else if ((sector == 1) && (layer == 31) && (component == 35)) {
                crate   = 79;
                slot    = 1;
                channel = 83;
        }
        else if ((sector == 1) && (layer == 32) && (component == 34)) {
                crate   = 79;
                slot    = 1;
                channel = 84;
        }
        else if ((sector == 1) && (layer == 31) && (component == 36)) {
                crate   = 79;
                slot    = 1;
                channel = 85;
        }
        else if ((sector == 1) && (layer == 31) && (component == 33)) {
                crate   = 79;
                slot    = 1;
                channel = 86;
        }
        else if ((sector == 1) && (layer == 22) && (component == 28)) {
                crate   = 79;
                slot    = 1;
                channel = 87;
        }
        else if ((sector == 1) && (layer == 31) && (component == 34)) {
                crate   = 79;
                slot    = 1;
                channel = 88;
        }
        else if ((sector == 1) && (layer == 21) && (component == 28)) {
                crate   = 79;
                slot    = 1;
                channel = 89;
        }
        else if ((sector == 1) && (layer == 22) && (component == 26)) {
                crate   = 79;
                slot    = 1;
                channel = 90;
        }
        else if ((sector == 1) && (layer == 21) && (component == 29)) {
                crate   = 79;
                slot    = 1;
                channel = 91;
        }
        else if ((sector == 1) && (layer == 22) && (component == 27)) {
                crate   = 79;
                slot    = 1;
                channel = 92;
        }
        else if ((sector == 1) && (layer == 11) && (component == 23)) {
                crate   = 79;
                slot    = 1;
                channel = 93;
        }
        else if ((sector == 1) && (layer == 21) && (component == 27)) {
                crate   = 79;
                slot    = 1;
                channel = 94;
        }
        else if ((sector == 1) && (layer == 11) && (component == 24)) {
                crate   = 79;
                slot    = 1;
                channel = 95;
        }
        else if ((sector == 1) && (layer == 11) && (component == 22)) {
                crate   = 79;
                slot    = 1;
                channel = 96;
        }
        else if ((sector == 1) && (layer == 51) && (component == 50)) {
                crate   = 79;
                slot    = 1;
                channel = 97;
        }
        else if ((sector == 1) && (layer == 51) && (component == 53)) {
                crate   = 79;
                slot    = 1;
                channel = 98;
        }
        else if ((sector == 1) && (layer == 51) && (component == 51)) {
                crate   = 79;
                slot    = 1;
                channel = 99;
        }
        else if ((sector == 1) && (layer == 51) && (component == 54)) {
                crate   = 79;
                slot    = 1;
                channel = 100;
        }
        else if ((sector == 1) && (layer == 51) && (component == 52)) {
                crate   = 79;
                slot    = 1;
                channel = 101;
        }
        else if ((sector == 1) && (layer == 51) && (component == 55)) {
                crate   = 79;
                slot    = 1;
                channel = 102;
        }
        else if ((sector == 1) && (layer == 42) && (component == 44)) {
                crate   = 79;
                slot    = 1;
                channel = 103;
        }
        else if ((sector == 1) && (layer == 42) && (component == 47)) {
                crate   = 79;
                slot    = 1;
                channel = 104;
        }
        else if ((sector == 1) && (layer == 42) && (component == 45)) {
                crate   = 79;
                slot    = 1;
                channel = 105;
        }
        else if ((sector == 1) && (layer == 42) && (component == 48)) {
                crate   = 79;
                slot    = 1;
                channel = 106;
        }
        else if ((sector == 1) && (layer == 42) && (component == 46)) {
                crate   = 79;
                slot    = 1;
                channel = 107;
        }
        else if ((sector == 1) && (layer == 41) && (component == 46)) {
                crate   = 79;
                slot    = 1;
                channel = 108;
        }
        else if ((sector == 1) && (layer == 41) && (component == 44)) {
                crate   = 79;
                slot    = 1;
                channel = 109;
        }
        else if ((sector == 1) && (layer == 41) && (component == 47)) {
                crate   = 79;
                slot    = 1;
                channel = 110;
        }
        else if ((sector == 1) && (layer == 41) && (component == 45)) {
                crate   = 79;
                slot    = 1;
                channel = 111;
        }
        else if ((sector == 1) && (layer == 41) && (component == 48)) {
                crate   = 79;
                slot    = 1;
                channel = 112;
        }
        else if ((sector == 1) && (layer == 32) && (component == 37)) {
                crate   = 79;
                slot    = 1;
                channel = 113;
        }
        else if ((sector == 1) && (layer == 32) && (component == 39)) {
                crate   = 79;
                slot    = 1;
                channel = 114;
        }
        else if ((sector == 1) && (layer == 32) && (component == 38)) {
                crate   = 79;
                slot    = 1;
                channel = 115;
        }
        else if ((sector == 1) && (layer == 32) && (component == 40)) {
                crate   = 79;
                slot    = 1;
                channel = 116;
        }
        else if ((sector == 1) && (layer == 31) && (component == 37)) {
                crate   = 79;
                slot    = 1;
                channel = 117;
        }
        else if ((sector == 1) && (layer == 31) && (component == 39)) {
                crate   = 79;
                slot    = 1;
                channel = 118;
        }
        else if ((sector == 1) && (layer == 31) && (component == 38)) {
                crate   = 79;
                slot    = 1;
                channel = 119;
        }
        else if ((sector == 1) && (layer == 31) && (component == 40)) {
                crate   = 79;
                slot    = 1;
                channel = 120;
        }
        else if ((sector == 1) && (layer == 22) && (component == 29)) {
                crate   = 79;
                slot    = 1;
                channel = 121;
        }
        else if ((sector == 1) && (layer == 22) && (component == 31)) {
                crate   = 79;
                slot    = 1;
                channel = 122;
        }
        else if ((sector == 1) && (layer == 22) && (component == 30)) {
                crate   = 79;
                slot    = 1;
                channel = 123;
        }
        else if ((sector == 1) && (layer == 21) && (component == 31)) {
                crate   = 79;
                slot    = 1;
                channel = 124;
        }
        else if ((sector == 1) && (layer == 21) && (component == 30)) {
                crate   = 79;
                slot    = 1;
                channel = 125;
        }
        else if ((sector == 1) && (layer == 21) && (component == 32)) {
                crate   = 79;
                slot    = 1;
                channel = 126;
        }
        else if ((sector == 1) && (layer == 11) && (component == 25)) {
                crate   = 79;
                slot    = 1;
                channel = 127;
        }
        else if ((sector == 1) && (layer == 11) && (component == 26)) {
                crate   = 79;
                slot    = 1;
                channel = 128;
        }
        else if ((sector == 1) && (layer == 51) && (component == 35)) {
                crate   = 79;
                slot    = 1;
                channel = 1;
        }
        else if ((sector == 1) && (layer == 51) && (component == 33)) {
                crate   = 79;
                slot    = 1;
                channel = 2;
        }
        else if ((sector == 1) && (layer == 51) && (component == 36)) {
                crate   = 79;
                slot    = 1;
                channel = 3;
        }
        else if ((sector == 1) && (layer == 51) && (component == 34)) {
                crate   = 79;
                slot    = 1;
                channel = 4;
        }
        else if ((sector == 1) && (layer == 51) && (component == 37)) {
                crate   = 79;
                slot    = 1;
                channel = 5;
        }
        else if ((sector == 1) && (layer == 42) && (component == 30)) {
                crate   = 79;
                slot    = 1;
                channel = 6;
        }
        else if ((sector == 1) && (layer == 42) && (component == 33)) {
                crate   = 79;
                slot    = 1;
                channel = 7;
        }
        else if ((sector == 1) && (layer == 42) && (component == 31)) {
                crate   = 79;
                slot    = 1;
                channel = 8;
        }
        else if ((sector == 1) && (layer == 42) && (component == 34)) {
                crate   = 79;
                slot    = 1;
                channel = 9;
        }
        else if ((sector == 1) && (layer == 42) && (component == 32)) {
                crate   = 79;
                slot    = 1;
                channel = 10;
        }
        else if ((sector == 1) && (layer == 41) && (component == 32)) {
                crate   = 79;
                slot    = 1;
                channel = 11;
        }
        else if ((sector == 1) && (layer == 41) && (component == 30)) {
                crate   = 79;
                slot    = 1;
                channel = 12;
        }
        else if ((sector == 1) && (layer == 41) && (component == 33)) {
                crate   = 79;
                slot    = 1;
                channel = 13;
        }
        else if ((sector == 1) && (layer == 41) && (component == 31)) {
                crate   = 79;
                slot    = 1;
                channel = 14;
        }
        else if ((sector == 1) && (layer == 32) && (component == 27)) {
                crate   = 79;
                slot    = 1;
                channel = 15;
        }
        else if ((sector == 1) && (layer == 32) && (component == 25)) {
                crate   = 79;
                slot    = 1;
                channel = 16;
        }
        else if ((sector == 1) && (layer == 32) && (component == 28)) {
                crate   = 79;
                slot    = 1;
                channel = 17;
        }
        else if ((sector == 1) && (layer == 32) && (component == 26)) {
                crate   = 79;
                slot    = 1;
                channel = 18;
        }
        else if ((sector == 1) && (layer == 31) && (component == 27)) {
                crate   = 79;
                slot    = 1;
                channel = 19;
        }
        else if ((sector == 1) && (layer == 31) && (component == 25)) {
                crate   = 79;
                slot    = 1;
                channel = 20;
        }
        else if ((sector == 1) && (layer == 31) && (component == 28)) {
                crate   = 79;
                slot    = 1;
                channel = 21;
        }
        else if ((sector == 1) && (layer == 31) && (component == 26)) {
                crate   = 79;
                slot    = 1;
                channel = 22;
        }
        else if ((sector == 1) && (layer == 22) && (component == 20)) {
                crate   = 79;
                slot    = 1;
                channel = 23;
        }
        else if ((sector == 1) && (layer == 22) && (component == 22)) {
                crate   = 79;
                slot    = 1;
                channel = 24;
        }
        else if ((sector == 1) && (layer == 21) && (component == 22)) {
                crate   = 79;
                slot    = 1;
                channel = 25;
        }
        else if ((sector == 1) && (layer == 22) && (component == 21)) {
                crate   = 79;
                slot    = 1;
                channel = 26;
        }
        else if ((sector == 1) && (layer == 21) && (component == 23)) {
                crate   = 79;
                slot    = 1;
                channel = 27;
        }
        else if ((sector == 1) && (layer == 21) && (component == 20)) {
                crate   = 79;
                slot    = 1;
                channel = 28;
        }
        else if ((sector == 1) && (layer == 11) && (component == 18)) {
                crate   = 79;
                slot    = 1;
                channel = 29;
        }
        else if ((sector == 1) && (layer == 21) && (component == 21)) {
                crate   = 79;
                slot    = 1;
                channel = 30;
        }
        else if ((sector == 1) && (layer == 11) && (component == 19)) {
                crate   = 79;
                slot    = 1;
                channel = 31;
        }
        else if ((sector == 1) && (layer == 11) && (component == 17)) {
                crate   = 79;
                slot    = 1;
                channel = 32;
        }
        else if ((sector == 1) && (layer == 51) && (component == 38)) {
                crate   = 79;
                slot    = 1;
                channel = 33;
        }
        else if ((sector == 1) && (layer == 51) && (component == 41)) {
                crate   = 79;
                slot    = 1;
                channel = 34;
        }
        else if ((sector == 1) && (layer == 51) && (component == 39)) {
                crate   = 79;
                slot    = 1;
                channel = 35;
        }
        else if ((sector == 1) && (layer == 51) && (component == 42)) {
                crate   = 79;
                slot    = 1;
                channel = 36;
        }
        else if ((sector == 1) && (layer == 51) && (component == 40)) {
                crate   = 79;
                slot    = 1;
                channel = 37;
        }
        else if ((sector == 1) && (layer == 51) && (component == 43)) {
                crate   = 79;
                slot    = 1;
                channel = 38;
        }
        else if ((sector == 1) && (layer == 42) && (component == 35)) {
                crate   = 79;
                slot    = 1;
                channel = 39;
        }
        else if ((sector == 1) && (layer == 42) && (component == 38)) {
                crate   = 79;
                slot    = 1;
                channel = 40;
        }
        else if ((sector == 1) && (layer == 42) && (component == 36)) {
                crate   = 79;
                slot    = 1;
                channel = 41;
        }
        else if ((sector == 1) && (layer == 42) && (component == 39)) {
                crate   = 79;
                slot    = 1;
                channel = 42;
        }
        else if ((sector == 1) && (layer == 42) && (component == 37)) {
                crate   = 79;
                slot    = 1;
                channel = 43;
        }
        else if ((sector == 1) && (layer == 41) && (component == 36)) {
                crate   = 79;
                slot    = 1;
                channel = 44;
        }
        else if ((sector == 1) && (layer == 41) && (component == 34)) {
                crate   = 79;
                slot    = 1;
                channel = 45;
        }
        else if ((sector == 1) && (layer == 41) && (component == 37)) {
                crate   = 79;
                slot    = 1;
                channel = 46;
        }
        else if ((sector == 1) && (layer == 41) && (component == 35)) {
                crate   = 79;
                slot    = 1;
                channel = 47;
        }
        else if ((sector == 1) && (layer == 41) && (component == 38)) {
                crate   = 79;
                slot    = 1;
                channel = 48;
        }
        else if ((sector == 1) && (layer == 32) && (component == 29)) {
                crate   = 79;
                slot    = 1;
                channel = 49;
        }
        else if ((sector == 1) && (layer == 32) && (component == 31)) {
                crate   = 79;
                slot    = 1;
                channel = 50;
        }
        else if ((sector == 1) && (layer == 32) && (component == 30)) {
                crate   = 79;
                slot    = 1;
                channel = 51;
        }
        else if ((sector == 1) && (layer == 32) && (component == 32)) {
                crate   = 79;
                slot    = 1;
                channel = 52;
        }
        else if ((sector == 1) && (layer == 31) && (component == 29)) {
                crate   = 79;
                slot    = 1;
                channel = 53;
        }
        else if ((sector == 1) && (layer == 31) && (component == 31)) {
                crate   = 79;
                slot    = 1;
                channel = 54;
        }
        else if ((sector == 1) && (layer == 31) && (component == 30)) {
                crate   = 79;
                slot    = 1;
                channel = 55;
        }
        else if ((sector == 1) && (layer == 31) && (component == 32)) {
                crate   = 79;
                slot    = 1;
                channel = 56;
        }
        else if ((sector == 1) && (layer == 22) && (component == 23)) {
                crate   = 79;
                slot    = 1;
                channel = 57;
        }
        else if ((sector == 1) && (layer == 22) && (component == 25)) {
                crate   = 79;
                slot    = 1;
                channel = 58;
        }
        else if ((sector == 1) && (layer == 22) && (component == 24)) {
                crate   = 79;
                slot    = 1;
                channel = 59;
        }
        else if ((sector == 1) && (layer == 21) && (component == 25)) {
                crate   = 79;
                slot    = 1;
                channel = 60;
        }
        else if ((sector == 1) && (layer == 21) && (component == 24)) {
                crate   = 79;
                slot    = 1;
                channel = 61;
        }
        else if ((sector == 1) && (layer == 21) && (component == 26)) {
                crate   = 79;
                slot    = 1;
                channel = 62;
        }
        else if ((sector == 1) && (layer == 11) && (component == 20)) {
                crate   = 79;
                slot    = 1;
                channel = 63;
        }
        else if ((sector == 1) && (layer == 11) && (component == 21)) {
                crate   = 79;
                slot    = 1;
                channel = 64;
        }
        else if ((sector == 1) && (layer == 51) && (component == 25)) {
                crate   = 79;
                slot    = 1;
                channel = 193;
        }
        else if ((sector == 1) && (layer == 51) && (component == 22)) {
                crate   = 79;
                slot    = 1;
                channel = 194;
        }
        else if ((sector == 1) && (layer == 51) && (component == 26)) {
                crate   = 79;
                slot    = 1;
                channel = 195;
        }
        else if ((sector == 1) && (layer == 51) && (component == 23)) {
                crate   = 79;
                slot    = 1;
                channel = 196;
        }
        else if ((sector == 1) && (layer == 42) && (component == 24)) {
                crate   = 79;
                slot    = 1;
                channel = 197;
        }
        else if ((sector == 1) && (layer == 51) && (component == 24)) {
                crate   = 79;
                slot    = 1;
                channel = 198;
        }
        else if ((sector == 1) && (layer == 41) && (component == 22)) {
                crate   = 79;
                slot    = 1;
                channel = 199;
        }
        else if ((sector == 1) && (layer == 42) && (component == 21)) {
                crate   = 79;
                slot    = 1;
                channel = 200;
        }
        else if ((sector == 1) && (layer == 41) && (component == 23)) {
                crate   = 79;
                slot    = 1;
                channel = 201;
        }
        else if ((sector == 1) && (layer == 42) && (component == 22)) {
                crate   = 79;
                slot    = 1;
                channel = 202;
        }
        else if ((sector == 1) && (layer == 41) && (component == 24)) {
                crate   = 79;
                slot    = 1;
                channel = 203;
        }
        else if ((sector == 1) && (layer == 42) && (component == 23)) {
                crate   = 79;
                slot    = 1;
                channel = 204;
        }
        else if ((sector == 1) && (layer == 32) && (component == 19)) {
                crate   = 79;
                slot    = 1;
                channel = 205;
        }
        else if ((sector == 1) && (layer == 41) && (component == 20)) {
                crate   = 79;
                slot    = 1;
                channel = 206;
        }
        else if ((sector == 1) && (layer == 32) && (component == 20)) {
                crate   = 79;
                slot    = 1;
                channel = 207;
        }
        else if ((sector == 1) && (layer == 41) && (component == 21)) {
                crate   = 79;
                slot    = 1;
                channel = 208;
        }
        else if ((sector == 1) && (layer == 31) && (component == 19)) {
                crate   = 79;
                slot    = 1;
                channel = 209;
        }
        else if ((sector == 1) && (layer == 32) && (component == 17)) {
                crate   = 79;
                slot    = 1;
                channel = 210;
        }
        else if ((sector == 1) && (layer == 31) && (component == 20)) {
                crate   = 79;
                slot    = 1;
                channel = 211;
        }
        else if ((sector == 1) && (layer == 32) && (component == 18)) {
                crate   = 79;
                slot    = 1;
                channel = 212;
        }
        else if ((sector == 1) && (layer == 22) && (component == 16)) {
                crate   = 79;
                slot    = 1;
                channel = 213;
        }
        else if ((sector == 1) && (layer == 31) && (component == 17)) {
                crate   = 79;
                slot    = 1;
                channel = 214;
        }
        else if ((sector == 1) && (layer == 21) && (component == 15)) {
                crate   = 79;
                slot    = 1;
                channel = 215;
        }
        else if ((sector == 1) && (layer == 31) && (component == 18)) {
                crate   = 79;
                slot    = 1;
                channel = 216;
        }
        else if ((sector == 1) && (layer == 21) && (component == 16)) {
                crate   = 79;
                slot    = 1;
                channel = 217;
        }
        else if ((sector == 1) && (layer == 22) && (component == 14)) {
                crate   = 79;
                slot    = 1;
                channel = 218;
        }
        else if ((sector == 1) && (layer == 11) && (component == 12)) {
                crate   = 79;
                slot    = 1;
                channel = 219;
        }
        else if ((sector == 1) && (layer == 22) && (component == 15)) {
                crate   = 79;
                slot    = 1;
                channel = 220;
        }
        else if ((sector == 1) && (layer == 11) && (component == 13)) {
                crate   = 79;
                slot    = 1;
                channel = 221;
        }
        else if ((sector == 1) && (layer == 21) && (component == 14)) {
                crate   = 79;
                slot    = 1;
                channel = 222;
        }
        else if ((sector == 1) && (layer == 11) && (component == 14)) {
                crate   = 79;
                slot    = 1;
                channel = 223;
        }
        else if ((sector == 1) && (layer == 11) && (component == 11)) {
                crate   = 79;
                slot    = 1;
                channel = 224;
        }
        else if ((sector == 1) && (layer == 51) && (component == 27)) {
                crate   = 79;
                slot    = 1;
                channel = 225;
        }
        else if ((sector == 1) && (layer == 51) && (component == 30)) {
                crate   = 79;
                slot    = 1;
                channel = 226;
        }
        else if ((sector == 1) && (layer == 51) && (component == 28)) {
                crate   = 79;
                slot    = 1;
                channel = 227;
        }
        else if ((sector == 1) && (layer == 51) && (component == 31)) {
                crate   = 79;
                slot    = 1;
                channel = 228;
        }
        else if ((sector == 1) && (layer == 51) && (component == 29)) {
                crate   = 79;
                slot    = 1;
                channel = 229;
        }
        else if ((sector == 1) && (layer == 51) && (component == 32)) {
                crate   = 79;
                slot    = 1;
                channel = 230;
        }
        else if ((sector == 1) && (layer == 42) && (component == 25)) {
                crate   = 79;
                slot    = 1;
                channel = 231;
        }
        else if ((sector == 1) && (layer == 42) && (component == 28)) {
                crate   = 79;
                slot    = 1;
                channel = 232;
        }
        else if ((sector == 1) && (layer == 42) && (component == 26)) {
                crate   = 79;
                slot    = 1;
                channel = 233;
        }
        else if ((sector == 1) && (layer == 42) && (component == 29)) {
                crate   = 79;
                slot    = 1;
                channel = 234;
        }
        else if ((sector == 1) && (layer == 42) && (component == 27)) {
                crate   = 79;
                slot    = 1;
                channel = 235;
        }
        else if ((sector == 1) && (layer == 41) && (component == 27)) {
                crate   = 79;
                slot    = 1;
                channel = 236;
        }
        else if ((sector == 1) && (layer == 41) && (component == 25)) {
                crate   = 79;
                slot    = 1;
                channel = 237;
        }
        else if ((sector == 1) && (layer == 41) && (component == 28)) {
                crate   = 79;
                slot    = 1;
                channel = 238;
        }
        else if ((sector == 1) && (layer == 41) && (component == 26)) {
                crate   = 79;
                slot    = 1;
                channel = 239;
        }
        else if ((sector == 1) && (layer == 41) && (component == 29)) {
                crate   = 79;
                slot    = 1;
                channel = 240;
        }
        else if ((sector == 1) && (layer == 32) && (component == 21)) {
                crate   = 79;
                slot    = 1;
                channel = 241;
        }
        else if ((sector == 1) && (layer == 32) && (component == 23)) {
                crate   = 79;
                slot    = 1;
                channel = 242;
        }
        else if ((sector == 1) && (layer == 32) && (component == 22)) {
                crate   = 79;
                slot    = 1;
                channel = 243;
        }
        else if ((sector == 1) && (layer == 32) && (component == 24)) {
                crate   = 79;
                slot    = 1;
                channel = 244;
        }
        else if ((sector == 1) && (layer == 31) && (component == 21)) {
                crate   = 79;
                slot    = 1;
                channel = 245;
        }
        else if ((sector == 1) && (layer == 31) && (component == 23)) {
                crate   = 79;
                slot    = 1;
                channel = 246;
        }
        else if ((sector == 1) && (layer == 31) && (component == 22)) {
                crate   = 79;
                slot    = 1;
                channel = 247;
        }
        else if ((sector == 1) && (layer == 31) && (component == 24)) {
                crate   = 79;
                slot    = 1;
                channel = 248;
        }
        else if ((sector == 1) && (layer == 22) && (component == 17)) {
                crate   = 79;
                slot    = 1;
                channel = 249;
        }
        else if ((sector == 1) && (layer == 22) && (component == 19)) {
                crate   = 79;
                slot    = 1;
                channel = 250;
        }
        else if ((sector == 1) && (layer == 22) && (component == 18)) {
                crate   = 79;
                slot    = 1;
                channel = 251;
        }
        else if ((sector == 1) && (layer == 21) && (component == 19)) {
                crate   = 79;
                slot    = 1;
                channel = 252;
        }
        else if ((sector == 1) && (layer == 21) && (component == 17)) {
                crate   = 79;
                slot    = 1;
                channel = 253;
        }
        else if ((sector == 1) && (layer == 21) && (component == 18)) {
                crate   = 79;
                slot    = 1;
                channel = 254;
        }
        else if ((sector == 1) && (layer == 11) && (component == 15)) {
                crate   = 79;
                slot    = 1;
                channel = 255;
        }
        else if ((sector == 1) && (layer == 11) && (component == 16)) {
                crate   = 79;
                slot    = 1;
                channel = 256;
        }
        else if ((sector == 1) && (layer == 51) && (component == 15)) {
                crate   = 79;
                slot    = 4;
                channel = 129;
        }
        else if ((sector == 1) && (layer == 51) && (component == 12)) {
                crate   = 79;
                slot    = 4;
                channel = 130;
        }
        else if ((sector == 1) && (layer == 51) && (component == 16)) {
                crate   = 79;
                slot    = 4;
                channel = 131;
        }
        else if ((sector == 1) && (layer == 51) && (component == 13)) {
                crate   = 79;
                slot    = 4;
                channel = 132;
        }
        else if ((sector == 1) && (layer == 42) && (component == 14)) {
                crate   = 79;
                slot    = 4;
                channel = 133;
        }
        else if ((sector == 1) && (layer == 51) && (component == 14)) {
                crate   = 79;
                slot    = 4;
                channel = 134;
        }
        else if ((sector == 1) && (layer == 42) && (component == 15)) {
                crate   = 79;
                slot    = 4;
                channel = 135;
        }
        else if ((sector == 1) && (layer == 42) && (component == 11)) {
                crate   = 79;
                slot    = 4;
                channel = 136;
        }
        else if ((sector == 1) && (layer == 41) && (component == 12)) {
                crate   = 79;
                slot    = 4;
                channel = 137;
        }
        else if ((sector == 1) && (layer == 42) && (component == 12)) {
                crate   = 79;
                slot    = 4;
                channel = 138;
        }
        else if ((sector == 1) && (layer == 41) && (component == 13)) {
                crate   = 79;
                slot    = 4;
                channel = 139;
        }
        else if ((sector == 1) && (layer == 42) && (component == 13)) {
                crate   = 79;
                slot    = 4;
                channel = 140;
        }
        else if ((sector == 1) && (layer == 41) && (component == 14)) {
                crate   = 79;
                slot    = 4;
                channel = 141;
        }
        else if ((sector == 1) && (layer == 41) && (component == 10)) {
                crate   = 79;
                slot    = 4;
                channel = 142;
        }
        else if ((sector == 1) && (layer == 32) && (component == 11)) {
                crate   = 79;
                slot    = 4;
                channel = 143;
        }
        else if ((sector == 1) && (layer == 41) && (component == 11)) {
                crate   = 79;
                slot    = 4;
                channel = 144;
        }
        else if ((sector == 1) && (layer == 32) && (component == 12)) {
                crate   = 79;
                slot    = 4;
                channel = 145;
        }
        else if ((sector == 1) && (layer == 32) && (component == 9)) {
                crate   = 79;
                slot    = 4;
                channel = 146;
        }
        else if ((sector == 1) && (layer == 31) && (component == 11)) {
                crate   = 79;
                slot    = 4;
                channel = 147;
        }
        else if ((sector == 1) && (layer == 32) && (component == 10)) {
                crate   = 79;
                slot    = 4;
                channel = 148;
        }
        else if ((sector == 1) && (layer == 31) && (component == 12)) {
                crate   = 79;
                slot    = 4;
                channel = 149;
        }
        else if ((sector == 1) && (layer == 31) && (component == 9)) {
                crate   = 79;
                slot    = 4;
                channel = 150;
        }
        else if ((sector == 1) && (layer == 22) && (component == 9)) {
                crate   = 79;
                slot    = 4;
                channel = 151;
        }
        else if ((sector == 1) && (layer == 31) && (component == 10)) {
                crate   = 79;
                slot    = 4;
                channel = 152;
        }
        else if ((sector == 1) && (layer == 21) && (component == 9)) {
                crate   = 79;
                slot    = 4;
                channel = 153;
        }
        else if ((sector == 1) && (layer == 22) && (component == 7)) {
                crate   = 79;
                slot    = 4;
                channel = 154;
        }
        else if ((sector == 1) && (layer == 21) && (component == 10)) {
                crate   = 79;
                slot    = 4;
                channel = 155;
        }
        else if ((sector == 1) && (layer == 22) && (component == 8)) {
                crate   = 79;
                slot    = 4;
                channel = 156;
        }
        else if ((sector == 1) && (layer == 11) && (component == 7)) {
                crate   = 79;
                slot    = 4;
                channel = 157;
        }
        else if ((sector == 1) && (layer == 21) && (component == 8)) {
                crate   = 79;
                slot    = 4;
                channel = 158;
        }
        else if ((sector == 1) && (layer == 11) && (component == 8)) {
                crate   = 79;
                slot    = 4;
                channel = 159;
        }
        else if ((sector == 1) && (layer == 11) && (component == 6)) {
                crate   = 79;
                slot    = 4;
                channel = 160;
        }
        else if ((sector == 1) && (layer == 51) && (component == 17)) {
                crate   = 79;
                slot    = 4;
                channel = 161;
        }
        else if ((sector == 1) && (layer == 51) && (component == 20)) {
                crate   = 79;
                slot    = 4;
                channel = 162;
        }
        else if ((sector == 1) && (layer == 51) && (component == 18)) {
                crate   = 79;
                slot    = 4;
                channel = 163;
        }
        else if ((sector == 1) && (layer == 51) && (component == 21)) {
                crate   = 79;
                slot    = 4;
                channel = 164;
        }
        else if ((sector == 1) && (layer == 51) && (component == 19)) {
                crate   = 79;
                slot    = 4;
                channel = 165;
        }
        else if ((sector == 1) && (layer == 42) && (component == 19)) {
                crate   = 79;
                slot    = 4;
                channel = 166;
        }
        else if ((sector == 1) && (layer == 42) && (component == 16)) {
                crate   = 79;
                slot    = 4;
                channel = 167;
        }
        else if ((sector == 1) && (layer == 42) && (component == 20)) {
                crate   = 79;
                slot    = 4;
                channel = 168;
        }
        else if ((sector == 1) && (layer == 42) && (component == 17)) {
                crate   = 79;
                slot    = 4;
                channel = 169;
        }
        else if ((sector == 1) && (layer == 41) && (component == 17)) {
                crate   = 79;
                slot    = 4;
                channel = 170;
        }
        else if ((sector == 1) && (layer == 42) && (component == 18)) {
                crate   = 79;
                slot    = 4;
                channel = 171;
        }
        else if ((sector == 1) && (layer == 41) && (component == 18)) {
                crate   = 79;
                slot    = 4;
                channel = 172;
        }
        else if ((sector == 1) && (layer == 41) && (component == 15)) {
                crate   = 79;
                slot    = 4;
                channel = 173;
        }
        else if ((sector == 1) && (layer == 41) && (component == 19)) {
                crate   = 79;
                slot    = 4;
                channel = 174;
        }
        else if ((sector == 1) && (layer == 41) && (component == 16)) {
                crate   = 79;
                slot    = 4;
                channel = 175;
        }
        else if ((sector == 1) && (layer == 32) && (component == 15)) {
                crate   = 79;
                slot    = 4;
                channel = 176;
        }
        else if ((sector == 1) && (layer == 32) && (component == 13)) {
                crate   = 79;
                slot    = 4;
                channel = 177;
        }
        else if ((sector == 1) && (layer == 32) && (component == 16)) {
                crate   = 79;
                slot    = 4;
                channel = 178;
        }
        else if ((sector == 1) && (layer == 32) && (component == 14)) {
                crate   = 79;
                slot    = 4;
                channel = 179;
        }
        else if ((sector == 1) && (layer == 31) && (component == 15)) {
                crate   = 79;
                slot    = 4;
                channel = 180;
        }
        else if ((sector == 1) && (layer == 31) && (component == 13)) {
                crate   = 79;
                slot    = 4;
                channel = 181;
        }
        else if ((sector == 1) && (layer == 31) && (component == 16)) {
                crate   = 79;
                slot    = 4;
                channel = 182;
        }
        else if ((sector == 1) && (layer == 31) && (component == 14)) {
                crate   = 79;
                slot    = 4;
                channel = 183;
        }
        else if ((sector == 1) && (layer == 22) && (component == 12)) {
                crate   = 79;
                slot    = 4;
                channel = 184;
        }
        else if ((sector == 1) && (layer == 22) && (component == 10)) {
                crate   = 79;
                slot    = 4;
                channel = 185;
        }
        else if ((sector == 1) && (layer == 22) && (component == 13)) {
                crate   = 79;
                slot    = 4;
                channel = 186;
        }
        else if ((sector == 1) && (layer == 22) && (component == 11)) {
                crate   = 79;
                slot    = 4;
                channel = 187;
        }
        else if ((sector == 1) && (layer == 21) && (component == 12)) {
                crate   = 79;
                slot    = 4;
                channel = 188;
        }
        else if ((sector == 1) && (layer == 21) && (component == 11)) {
                crate   = 79;
                slot    = 4;
                channel = 189;
        }
        else if ((sector == 1) && (layer == 21) && (component == 13)) {
                crate   = 79;
                slot    = 4;
                channel = 190;
        }
        else if ((sector == 1) && (layer == 11) && (component == 9)) {
                crate   = 79;
                slot    = 4;
                channel = 191;
        }
        else if ((sector == 1) && (layer == 11) && (component == 10)) {
                crate   = 79;
                slot    = 4;
                channel = 192;
        }
        else if ((sector == 1) && (layer == 51) && (component == 3)) {
                crate   = 79;
                slot    = 1;
                channel = 321;
        }
        else if ((sector == 1) && (layer == 51) && (component == 99)) {
                crate   = 79;
                slot    = 1;
                channel = 322;
        }
        else if ((sector == 1) && (layer == 51) && (component == 4)) {
                crate   = 79;
                slot    = 1;
                channel = 323;
        }
        else if ((sector == 1) && (layer == 51) && (component == 1)) {
                crate   = 79;
                slot    = 1;
                channel = 324;
        }
        else if ((sector == 1) && (layer == 51) && (component == 5)) {
                crate   = 79;
                slot    = 1;
                channel = 325;
        }
        else if ((sector == 1) && (layer == 51) && (component == 2)) {
                crate   = 79;
                slot    = 1;
                channel = 326;
        }
        else if ((sector == 1) && (layer == 42) && (component == 4)) {
                crate   = 79;
                slot    = 1;
                channel = 327;
        }
        else if ((sector == 1) && (layer == 42) && (component == 1)) {
                crate   = 79;
                slot    = 1;
                channel = 328;
        }
        else if ((sector == 1) && (layer == 42) && (component == 5)) {
                crate   = 79;
                slot    = 1;
                channel = 329;
        }
        else if ((sector == 1) && (layer == 42) && (component == 2)) {
                crate   = 79;
                slot    = 1;
                channel = 330;
        }
        else if ((sector == 1) && (layer == 41) && (component == 3)) {
                crate   = 79;
                slot    = 1;
                channel = 331;
        }
        else if ((sector == 1) && (layer == 42) && (component == 3)) {
                crate   = 79;
                slot    = 1;
                channel = 332;
        }
        else if ((sector == 1) && (layer == 41) && (component == 4)) {
                crate   = 79;
                slot    = 1;
                channel = 333;
        }
        else if ((sector == 1) && (layer == 41) && (component == 1)) {
                crate   = 79;
                slot    = 1;
                channel = 334;
        }
        else if ((sector == 1) && (layer == 32) && (component == 3)) {
                crate   = 79;
                slot    = 1;
                channel = 335;
        }
        else if ((sector == 1) && (layer == 41) && (component == 2)) {
                crate   = 79;
                slot    = 1;
                channel = 336;
        }
        else if ((sector == 1) && (layer == 32) && (component == 4)) {
                crate   = 79;
                slot    = 1;
                channel = 337;
        }
        else if ((sector == 1) && (layer == 32) && (component == 1)) {
                crate   = 79;
                slot    = 1;
                channel = 338;
        }
        else if ((sector == 1) && (layer == 31) && (component == 3)) {
                crate   = 79;
                slot    = 1;
                channel = 339;
        }
        else if ((sector == 1) && (layer == 32) && (component == 2)) {
                crate   = 79;
                slot    = 1;
                channel = 340;
        }
        else if ((sector == 1) && (layer == 31) && (component == 4)) {
                crate   = 79;
                slot    = 1;
                channel = 341;
        }
        else if ((sector == 1) && (layer == 31) && (component == 1)) {
                crate   = 79;
                slot    = 1;
                channel = 342;
        }
        else if ((sector == 1) && (layer == 22) && (component == 3)) {
                crate   = 79;
                slot    = 1;
                channel = 343;
        }
        else if ((sector == 1) && (layer == 31) && (component == 2)) {
                crate   = 79;
                slot    = 1;
                channel = 344;
        }
        else if ((sector == 1) && (layer == 21) && (component == 3)) {
                crate   = 79;
                slot    = 1;
                channel = 345;
        }
        else if ((sector == 1) && (layer == 22) && (component == 1)) {
                crate   = 79;
                slot    = 1;
                channel = 346;
        }
        else if ((sector == 1) && (layer == 21) && (component == 4)) {
                crate   = 79;
                slot    = 1;
                channel = 347;
        }
        else if ((sector == 1) && (layer == 22) && (component == 2)) {
                crate   = 79;
                slot    = 1;
                channel = 348;
        }
        else if ((sector == 1) && (layer == 11) && (component == 2)) {
                crate   = 79;
                slot    = 1;
                channel = 349;
        }
        else if ((sector == 1) && (layer == 21) && (component == 2)) {
                crate   = 79;
                slot    = 1;
                channel = 350;
        }
        else if ((sector == 1) && (layer == 11) && (component == 3)) {
                crate   = 79;
                slot    = 1;
                channel = 351;
        }
        else if ((sector == 1) && (layer == 11) && (component == 1)) {
                crate   = 79;
                slot    = 1;
                channel = 352;
        }
        else if ((sector == 1) && (layer == 51) && (component == 6)) {
                crate   = 79;
                slot    = 1;
                channel = 353;
        }
        else if ((sector == 1) && (layer == 51) && (component == 9)) {
                crate   = 79;
                slot    = 1;
                channel = 354;
        }
        else if ((sector == 1) && (layer == 51) && (component == 7)) {
                crate   = 79;
                slot    = 1;
                channel = 355;
        }
        else if ((sector == 1) && (layer == 51) && (component == 10)) {
                crate   = 79;
                slot    = 1;
                channel = 356;
        }
        else if ((sector == 1) && (layer == 51) && (component == 8)) {
                crate   = 79;
                slot    = 1;
                channel = 357;
        }
        else if ((sector == 1) && (layer == 51) && (component == 11)) {
                crate   = 79;
                slot    = 1;
                channel = 358;
        }
        else if ((sector == 1) && (layer == 42) && (component == 6)) {
                crate   = 79;
                slot    = 1;
                channel = 359;
        }
        else if ((sector == 1) && (layer == 42) && (component == 9)) {
                crate   = 79;
                slot    = 1;
                channel = 360;
        }
        else if ((sector == 1) && (layer == 42) && (component == 7)) {
                crate   = 79;
                slot    = 1;
                channel = 361;
        }
        else if ((sector == 1) && (layer == 42) && (component == 10)) {
                crate   = 79;
                slot    = 1;
                channel = 362;
        }
        else if ((sector == 1) && (layer == 42) && (component == 8)) {
                crate   = 79;
                slot    = 1;
                channel = 363;
        }
        else if ((sector == 1) && (layer == 41) && (component == 7)) {
                crate   = 79;
                slot    = 1;
                channel = 364;
        }
        else if ((sector == 1) && (layer == 41) && (component == 5)) {
                crate   = 79;
                slot    = 1;
                channel = 365;
        }
        else if ((sector == 1) && (layer == 41) && (component == 8)) {
                crate   = 79;
                slot    = 1;
                channel = 366;
        }
        else if ((sector == 1) && (layer == 41) && (component == 6)) {
                crate   = 79;
                slot    = 1;
                channel = 367;
        }
        else if ((sector == 1) && (layer == 41) && (component == 9)) {
                crate   = 79;
                slot    = 1;
                channel = 368;
        }
        else if ((sector == 1) && (layer == 32) && (component == 5)) {
                crate   = 79;
                slot    = 1;
                channel = 369;
        }
        else if ((sector == 1) && (layer == 32) && (component == 7)) {
                crate   = 79;
                slot    = 1;
                channel = 370;
        }
        else if ((sector == 1) && (layer == 32) && (component == 6)) {
                crate   = 79;
                slot    = 1;
                channel = 371;
        }
        else if ((sector == 1) && (layer == 32) && (component == 8)) {
                crate   = 79;
                slot    = 1;
                channel = 372;
        }
        else if ((sector == 1) && (layer == 31) && (component == 5)) {
                crate   = 79;
                slot    = 1;
                channel = 373;
        }
        else if ((sector == 1) && (layer == 31) && (component == 7)) {
                crate   = 79;
                slot    = 1;
                channel = 374;
        }
        else if ((sector == 1) && (layer == 31) && (component == 6)) {
                crate   = 79;
                slot    = 1;
                channel = 375;
        }
        else if ((sector == 1) && (layer == 31) && (component == 8)) {
                crate   = 79;
                slot    = 1;
                channel = 376;
        }
        else if ((sector == 1) && (layer == 22) && (component == 4)) {
                crate   = 79;
                slot    = 1;
                channel = 377;
        }
        else if ((sector == 1) && (layer == 22) && (component == 6)) {
                crate   = 79;
                slot    = 1;
                channel = 378;
        }
        else if ((sector == 1) && (layer == 22) && (component == 5)) {
                crate   = 79;
                slot    = 1;
                channel = 379;
        }
        else if ((sector == 1) && (layer == 21) && (component == 6)) {
                crate   = 79;
                slot    = 1;
                channel = 380;
        }
        else if ((sector == 1) && (layer == 21) && (component == 5)) {
                crate   = 79;
                slot    = 1;
                channel = 381;
        }
        else if ((sector == 1) && (layer == 21) && (component == 7)) {
                crate   = 79;
                slot    = 1;
                channel = 382;
        }
        else if ((sector == 1) && (layer == 11) && (component == 4)) {
                crate   = 79;
                slot    = 1;
                channel = 383;
        }
        else if ((sector == 1) && (layer == 11) && (component == 5)) {
                crate   = 79;
                slot    = 1;
                channel = 384;
        }
        else if ((sector == 1) && (layer == 51) && (component == 91)) {
                crate   = 79;
                slot    = 4;
                channel = 257;
        }
        else if ((sector == 1) && (layer == 51) && (component == 88)) {
                crate   = 79;
                slot    = 4;
                channel = 258;
        }
        else if ((sector == 1) && (layer == 51) && (component == 92)) {
                crate   = 79;
                slot    = 4;
                channel = 259;
        }
        else if ((sector == 1) && (layer == 51) && (component == 89)) {
                crate   = 79;
                slot    = 4;
                channel = 260;
        }
        else if ((sector == 1) && (layer == 42) && (component == 81)) {
                crate   = 79;
                slot    = 4;
                channel = 261;
        }
        else if ((sector == 1) && (layer == 51) && (component == 90)) {
                crate   = 79;
                slot    = 4;
                channel = 262;
        }
        else if ((sector == 1) && (layer == 42) && (component == 82)) {
                crate   = 79;
                slot    = 4;
                channel = 263;
        }
        else if ((sector == 1) && (layer == 42) && (component == 78)) {
                crate   = 79;
                slot    = 4;
                channel = 264;
        }
        else if ((sector == 1) && (layer == 41) && (component == 80)) {
                crate   = 79;
                slot    = 4;
                channel = 265;
        }
        else if ((sector == 1) && (layer == 42) && (component == 79)) {
                crate   = 79;
                slot    = 4;
                channel = 266;
        }
        else if ((sector == 1) && (layer == 41) && (component == 81)) {
                crate   = 79;
                slot    = 4;
                channel = 267;
        }
        else if ((sector == 1) && (layer == 42) && (component == 80)) {
                crate   = 79;
                slot    = 4;
                channel = 268;
        }
        else if ((sector == 1) && (layer == 41) && (component == 82)) {
                crate   = 79;
                slot    = 4;
                channel = 269;
        }
        else if ((sector == 1) && (layer == 41) && (component == 78)) {
                crate   = 79;
                slot    = 4;
                channel = 270;
        }
        else if ((sector == 1) && (layer == 32) && (component == 67)) {
                crate   = 79;
                slot    = 4;
                channel = 271;
        }
        else if ((sector == 1) && (layer == 41) && (component == 79)) {
                crate   = 79;
                slot    = 4;
                channel = 272;
        }
        else if ((sector == 1) && (layer == 31) && (component == 68)) {
                crate   = 79;
                slot    = 4;
                channel = 273;
        }
        else if ((sector == 1) && (layer == 32) && (component == 65)) {
                crate   = 79;
                slot    = 4;
                channel = 274;
        }
        else if ((sector == 1) && (layer == 31) && (component == 67)) {
                crate   = 79;
                slot    = 4;
                channel = 275;
        }
        else if ((sector == 1) && (layer == 32) && (component == 66)) {
                crate   = 79;
                slot    = 4;
                channel = 276;
        }
        else if ((sector == 1) && (layer == 32) && (component == 68)) {
                crate   = 79;
                slot    = 4;
                channel = 277;
        }
        else if ((sector == 1) && (layer == 31) && (component == 65)) {
                crate   = 79;
                slot    = 4;
                channel = 278;
        }
        else if ((sector == 1) && (layer == 22) && (component == 53)) {
                crate   = 79;
                slot    = 4;
                channel = 279;
        }
        else if ((sector == 1) && (layer == 31) && (component == 66)) {
                crate   = 79;
                slot    = 4;
                channel = 280;
        }
        else if ((sector == 1) && (layer == 21) && (component == 53)) {
                crate   = 79;
                slot    = 4;
                channel = 281;
        }
        else if ((sector == 1) && (layer == 22) && (component == 51)) {
                crate   = 79;
                slot    = 4;
                channel = 282;
        }
        else if ((sector == 1) && (layer == 21) && (component == 54)) {
                crate   = 79;
                slot    = 4;
                channel = 283;
        }
        else if ((sector == 1) && (layer == 22) && (component == 52)) {
                crate   = 79;
                slot    = 4;
                channel = 284;
        }
        else if ((sector == 1) && (layer == 11) && (component == 44)) {
                crate   = 79;
                slot    = 4;
                channel = 285;
        }
        else if ((sector == 1) && (layer == 21) && (component == 52)) {
                crate   = 79;
                slot    = 4;
                channel = 286;
        }
        else if ((sector == 1) && (layer == 11) && (component == 45)) {
                crate   = 79;
                slot    = 4;
                channel = 287;
        }
        else if ((sector == 1) && (layer == 11) && (component == 43)) {
                crate   = 79;
                slot    = 4;
                channel = 288;
        }
        else if ((sector == 1) && (layer == 51) && (component == 93)) {
                crate   = 79;
                slot    = 4;
                channel = 289;
        }
        else if ((sector == 1) && (layer == 51) && (component == 96)) {
                crate   = 79;
                slot    = 4;
                channel = 290;
        }
        else if ((sector == 1) && (layer == 51) && (component == 94)) {
                crate   = 79;
                slot    = 4;
                channel = 291;
        }
        else if ((sector == 1) && (layer == 51) && (component == 97)) {
                crate   = 79;
                slot    = 4;
                channel = 292;
        }
        else if ((sector == 1) && (layer == 51) && (component == 95)) {
                crate   = 79;
                slot    = 4;
                channel = 293;
        }
        else if ((sector == 1) && (layer == 51) && (component == 98)) {
                crate   = 79;
                slot    = 4;
                channel = 294;
        }
        else if ((sector == 1) && (layer == 42) && (component == 83)) {
                crate   = 79;
                slot    = 4;
                channel = 295;
        }
        else if ((sector == 1) && (layer == 42) && (component == 86)) {
                crate   = 79;
                slot    = 4;
                channel = 296;
        }
        else if ((sector == 1) && (layer == 42) && (component == 84)) {
                crate   = 79;
                slot    = 4;
                channel = 297;
        }
        else if ((sector == 1) && (layer == 42) && (component == 87)) {
                crate   = 79;
                slot    = 4;
                channel = 298;
        }
        else if ((sector == 1) && (layer == 42) && (component == 85)) {
                crate   = 79;
                slot    = 4;
                channel = 299;
        }
        else if ((sector == 1) && (layer == 41) && (component == 85)) {
                crate   = 79;
                slot    = 4;
                channel = 300;
        }
        else if ((sector == 1) && (layer == 41) && (component == 83)) {
                crate   = 79;
                slot    = 4;
                channel = 301;
        }
        else if ((sector == 1) && (layer == 41) && (component == 86)) {
                crate   = 79;
                slot    = 4;
                channel = 302;
        }
        else if ((sector == 1) && (layer == 41) && (component == 84)) {
                crate   = 79;
                slot    = 4;
                channel = 303;
        }
        else if ((sector == 1) && (layer == 41) && (component == 87)) {
                crate   = 79;
                slot    = 4;
                channel = 304;
        }
        else if ((sector == 1) && (layer == 32) && (component == 69)) {
                crate   = 79;
                slot    = 4;
                channel = 305;
        }
        else if ((sector == 1) && (layer == 32) && (component == 71)) {
                crate   = 79;
                slot    = 4;
                channel = 306;
        }
        else if ((sector == 1) && (layer == 32) && (component == 70)) {
                crate   = 79;
                slot    = 4;
                channel = 307;
        }
        else if ((sector == 1) && (layer == 32) && (component == 72)) {
                crate   = 79;
                slot    = 4;
                channel = 308;
        }
        else if ((sector == 1) && (layer == 31) && (component == 69)) {
                crate   = 79;
                slot    = 4;
                channel = 309;
        }
        else if ((sector == 1) && (layer == 31) && (component == 71)) {
                crate   = 79;
                slot    = 4;
                channel = 310;
        }
        else if ((sector == 1) && (layer == 31) && (component == 70)) {
                crate   = 79;
                slot    = 4;
                channel = 311;
        }
        else if ((sector == 1) && (layer == 31) && (component == 72)) {
                crate   = 79;
                slot    = 4;
                channel = 312;
        }
        else if ((sector == 1) && (layer == 22) && (component == 54)) {
                crate   = 79;
                slot    = 4;
                channel = 313;
        }
        else if ((sector == 1) && (layer == 22) && (component == 56)) {
                crate   = 79;
                slot    = 4;
                channel = 314;
        }
        else if ((sector == 1) && (layer == 22) && (component == 55)) {
                crate   = 79;
                slot    = 4;
                channel = 315;
        }
        else if ((sector == 1) && (layer == 21) && (component == 56)) {
                crate   = 79;
                slot    = 4;
                channel = 316;
        }
        else if ((sector == 1) && (layer == 21) && (component == 55)) {
                crate   = 79;
                slot    = 4;
                channel = 317;
        }
        else if ((sector == 1) && (layer == 21) && (component == 1)) {
                crate   = 79;
                slot    = 4;
                channel = 318;
        }
        else if ((sector == 1) && (layer == 11) && (component == 46)) {
                crate   = 79;
                slot    = 4;
                channel = 319;
        }
        else if ((sector == 1) && (layer == 11) && (component == 47)) {
                crate   = 79;
                slot    = 4;
                channel = 320;
        }
        else if ((sector == 1) && (layer == 51) && (component == 80)) {
                crate   = 79;
                slot    = 1;
                channel = 449;
        }
        else if ((sector == 1) && (layer == 51) && (component == 77)) {
                crate   = 79;
                slot    = 1;
                channel = 450;
        }
        else if ((sector == 1) && (layer == 51) && (component == 81)) {
                crate   = 79;
                slot    = 1;
                channel = 451;
        }
        else if ((sector == 1) && (layer == 51) && (component == 78)) {
                crate   = 79;
                slot    = 1;
                channel = 452;
        }
        else if ((sector == 1) && (layer == 42) && (component == 71)) {
                crate   = 79;
                slot    = 1;
                channel = 453;
        }
        else if ((sector == 1) && (layer == 51) && (component == 79)) {
                crate   = 79;
                slot    = 1;
                channel = 454;
        }
        else if ((sector == 1) && (layer == 42) && (component == 72)) {
                crate   = 79;
                slot    = 1;
                channel = 455;
        }
        else if ((sector == 1) && (layer == 42) && (component == 69)) {
                crate   = 79;
                slot    = 1;
                channel = 456;
        }
        else if ((sector == 1) && (layer == 41) && (component == 70)) {
                crate   = 79;
                slot    = 1;
                channel = 457;
        }
        else if ((sector == 1) && (layer == 42) && (component == 70)) {
                crate   = 79;
                slot    = 1;
                channel = 458;
        }
        else if ((sector == 1) && (layer == 41) && (component == 71)) {
                crate   = 79;
                slot    = 1;
                channel = 459;
        }
        else if ((sector == 1) && (layer == 41) && (component == 68)) {
                crate   = 79;
                slot    = 1;
                channel = 460;
        }
        else if ((sector == 1) && (layer == 41) && (component == 72)) {
                crate   = 79;
                slot    = 1;
                channel = 461;
        }
        else if ((sector == 1) && (layer == 41) && (component == 69)) {
                crate   = 79;
                slot    = 1;
                channel = 462;
        }
        else if ((sector == 1) && (layer == 32) && (component == 59)) {
                crate   = 79;
                slot    = 1;
                channel = 463;
        }
        else if ((sector == 1) && (layer == 32) && (component == 57)) {
                crate   = 79;
                slot    = 1;
                channel = 464;
        }
        else if ((sector == 1) && (layer == 32) && (component == 60)) {
                crate   = 79;
                slot    = 1;
                channel = 465;
        }
        else if ((sector == 1) && (layer == 32) && (component == 58)) {
                crate   = 79;
                slot    = 1;
                channel = 466;
        }
        else if ((sector == 1) && (layer == 31) && (component == 59)) {
                crate   = 79;
                slot    = 1;
                channel = 467;
        }
        else if ((sector == 1) && (layer == 31) && (component == 57)) {
                crate   = 79;
                slot    = 1;
                channel = 468;
        }
        else if ((sector == 1) && (layer == 31) && (component == 60)) {
                crate   = 79;
                slot    = 1;
                channel = 469;
        }
        else if ((sector == 1) && (layer == 31) && (component == 58)) {
                crate   = 79;
                slot    = 1;
                channel = 470;
        }
        else if ((sector == 1) && (layer == 22) && (component == 47)) {
                crate   = 79;
                slot    = 1;
                channel = 471;
        }
        else if ((sector == 1) && (layer == 22) && (component == 45)) {
                crate   = 79;
                slot    = 1;
                channel = 472;
        }
        else if ((sector == 1) && (layer == 21) && (component == 47)) {
                crate   = 79;
                slot    = 1;
                channel = 473;
        }
        else if ((sector == 1) && (layer == 22) && (component == 46)) {
                crate   = 79;
                slot    = 1;
                channel = 474;
        }
        else if ((sector == 1) && (layer == 21) && (component == 48)) {
                crate   = 79;
                slot    = 1;
                channel = 475;
        }
        else if ((sector == 1) && (layer == 21) && (component == 45)) {
                crate   = 79;
                slot    = 1;
                channel = 476;
        }
        else if ((sector == 1) && (layer == 11) && (component == 39)) {
                crate   = 79;
                slot    = 1;
                channel = 477;
        }
        else if ((sector == 1) && (layer == 21) && (component == 46)) {
                crate   = 79;
                slot    = 1;
                channel = 478;
        }
        else if ((sector == 1) && (layer == 11) && (component == 40)) {
                crate   = 79;
                slot    = 1;
                channel = 479;
        }
        else if ((sector == 1) && (layer == 11) && (component == 38)) {
                crate   = 79;
                slot    = 1;
                channel = 480;
        }
        else if ((sector == 1) && (layer == 51) && (component == 82)) {
                crate   = 79;
                slot    = 1;
                channel = 481;
        }
        else if ((sector == 1) && (layer == 51) && (component == 85)) {
                crate   = 79;
                slot    = 1;
                channel = 482;
        }
        else if ((sector == 1) && (layer == 51) && (component == 83)) {
                crate   = 79;
                slot    = 1;
                channel = 483;
        }
        else if ((sector == 1) && (layer == 51) && (component == 86)) {
                crate   = 79;
                slot    = 1;
                channel = 484;
        }
        else if ((sector == 1) && (layer == 51) && (component == 84)) {
                crate   = 79;
                slot    = 1;
                channel = 485;
        }
        else if ((sector == 1) && (layer == 51) && (component == 87)) {
                crate   = 79;
                slot    = 1;
                channel = 486;
        }
        else if ((sector == 1) && (layer == 42) && (component == 73)) {
                crate   = 79;
                slot    = 1;
                channel = 487;
        }
        else if ((sector == 1) && (layer == 42) && (component == 76)) {
                crate   = 79;
                slot    = 1;
                channel = 488;
        }
        else if ((sector == 1) && (layer == 42) && (component == 74)) {
                crate   = 79;
                slot    = 1;
                channel = 489;
        }
        else if ((sector == 1) && (layer == 42) && (component == 77)) {
                crate   = 79;
                slot    = 1;
                channel = 490;
        }
        else if ((sector == 1) && (layer == 42) && (component == 75)) {
                crate   = 79;
                slot    = 1;
                channel = 491;
        }
        else if ((sector == 1) && (layer == 41) && (component == 75)) {
                crate   = 79;
                slot    = 1;
                channel = 492;
        }
        else if ((sector == 1) && (layer == 41) && (component == 73)) {
                crate   = 79;
                slot    = 1;
                channel = 493;
        }
        else if ((sector == 1) && (layer == 41) && (component == 76)) {
                crate   = 79;
                slot    = 1;
                channel = 494;
        }
        else if ((sector == 1) && (layer == 41) && (component == 74)) {
                crate   = 79;
                slot    = 1;
                channel = 495;
        }
        else if ((sector == 1) && (layer == 41) && (component == 77)) {
                crate   = 79;
                slot    = 1;
                channel = 496;
        }
        else if ((sector == 1) && (layer == 32) && (component == 61)) {
                crate   = 79;
                slot    = 1;
                channel = 497;
        }
        else if ((sector == 1) && (layer == 32) && (component == 63)) {
                crate   = 79;
                slot    = 1;
                channel = 498;
        }
        else if ((sector == 1) && (layer == 32) && (component == 62)) {
                crate   = 79;
                slot    = 1;
                channel = 499;
        }
        else if ((sector == 1) && (layer == 32) && (component == 64)) {
                crate   = 79;
                slot    = 1;
                channel = 500;
        }
        else if ((sector == 1) && (layer == 31) && (component == 61)) {
                crate   = 79;
                slot    = 1;
                channel = 501;
        }
        else if ((sector == 1) && (layer == 31) && (component == 63)) {
                crate   = 79;
                slot    = 1;
                channel = 502;
        }
        else if ((sector == 1) && (layer == 31) && (component == 62)) {
                crate   = 79;
                slot    = 1;
                channel = 503;
        }
        else if ((sector == 1) && (layer == 31) && (component == 64)) {
                crate   = 79;
                slot    = 1;
                channel = 504;
        }
        else if ((sector == 1) && (layer == 22) && (component == 48)) {
                crate   = 79;
                slot    = 1;
                channel = 505;
        }
        else if ((sector == 1) && (layer == 22) && (component == 50)) {
                crate   = 79;
                slot    = 1;
                channel = 506;
        }
        else if ((sector == 1) && (layer == 22) && (component == 49)) {
                crate   = 79;
                slot    = 1;
                channel = 507;
        }
        else if ((sector == 1) && (layer == 21) && (component == 50)) {
                crate   = 79;
                slot    = 1;
                channel = 508;
        }
        else if ((sector == 1) && (layer == 21) && (component == 49)) {
                crate   = 79;
                slot    = 1;
                channel = 509;
        }
        else if ((sector == 1) && (layer == 21) && (component == 51)) {
                crate   = 79;
                slot    = 1;
                channel = 510;
        }
        else if ((sector == 1) && (layer == 11) && (component == 41)) {
                crate   = 79;
                slot    = 1;
                channel = 511;
        }
        else if ((sector == 1) && (layer == 11) && (component == 42)) {
                crate   = 79;
                slot    = 1;
                channel = 512;
        }
        else if ((sector == 1) && (layer == 51) && (component == 70)) {
                crate   = 79;
                slot    = 4;
                channel = 385;
        }
        else if ((sector == 1) && (layer == 51) && (component == 67)) {
                crate   = 79;
                slot    = 4;
                channel = 386;
        }
        else if ((sector == 1) && (layer == 51) && (component == 71)) {
                crate   = 79;
                slot    = 4;
                channel = 387;
        }
        else if ((sector == 1) && (layer == 51) && (component == 68)) {
                crate   = 79;
                slot    = 4;
                channel = 388;
        }
        else if ((sector == 1) && (layer == 42) && (component == 62)) {
                crate   = 79;
                slot    = 4;
                channel = 389;
        }
        else if ((sector == 1) && (layer == 51) && (component == 69)) {
                crate   = 79;
                slot    = 4;
                channel = 390;
        }
        else if ((sector == 1) && (layer == 42) && (component == 63)) {
                crate   = 79;
                slot    = 4;
                channel = 391;
        }
        else if ((sector == 1) && (layer == 42) && (component == 59)) {
                crate   = 79;
                slot    = 4;
                channel = 392;
        }
        else if ((sector == 1) && (layer == 41) && (component == 61)) {
                crate   = 79;
                slot    = 4;
                channel = 393;
        }
        else if ((sector == 1) && (layer == 42) && (component == 60)) {
                crate   = 79;
                slot    = 4;
                channel = 394;
        }
        else if ((sector == 1) && (layer == 41) && (component == 62)) {
                crate   = 79;
                slot    = 4;
                channel = 395;
        }
        else if ((sector == 1) && (layer == 42) && (component == 61)) {
                crate   = 79;
                slot    = 4;
                channel = 396;
        }
        else if ((sector == 1) && (layer == 32) && (component == 51)) {
                crate   = 79;
                slot    = 4;
                channel = 397;
        }
        else if ((sector == 1) && (layer == 41) && (component == 59)) {
                crate   = 79;
                slot    = 4;
                channel = 398;
        }
        else if ((sector == 1) && (layer == 32) && (component == 52)) {
                crate   = 79;
                slot    = 4;
                channel = 399;
        }
        else if ((sector == 1) && (layer == 41) && (component == 60)) {
                crate   = 79;
                slot    = 4;
                channel = 400;
        }
        else if ((sector == 1) && (layer == 31) && (component == 51)) {
                crate   = 79;
                slot    = 4;
                channel = 401;
        }
        else if ((sector == 1) && (layer == 32) && (component == 49)) {
                crate   = 79;
                slot    = 4;
                channel = 402;
        }
        else if ((sector == 1) && (layer == 31) && (component == 52)) {
                crate   = 79;
                slot    = 4;
                channel = 403;
        }
        else if ((sector == 1) && (layer == 32) && (component == 50)) {
                crate   = 79;
                slot    = 4;
                channel = 404;
        }
        else if ((sector == 1) && (layer == 22) && (component == 40)) {
                crate   = 79;
                slot    = 4;
                channel = 405;
        }
        else if ((sector == 1) && (layer == 31) && (component == 49)) {
                crate   = 79;
                slot    = 4;
                channel = 406;
        }
        else if ((sector == 1) && (layer == 21) && (component == 40)) {
                crate   = 79;
                slot    = 4;
                channel = 407;
        }
        else if ((sector == 1) && (layer == 31) && (component == 50)) {
                crate   = 79;
                slot    = 4;
                channel = 408;
        }
        else if ((sector == 1) && (layer == 21) && (component == 41)) {
                crate   = 79;
                slot    = 4;
                channel = 409;
        }
        else if ((sector == 1) && (layer == 22) && (component == 38)) {
                crate   = 79;
                slot    = 4;
                channel = 410;
        }
        else if ((sector == 1) && (layer == 11) && (component == 33)) {
                crate   = 79;
                slot    = 4;
                channel = 411;
        }
        else if ((sector == 1) && (layer == 22) && (component == 39)) {
                crate   = 79;
                slot    = 4;
                channel = 412;
        }
        else if ((sector == 1) && (layer == 11) && (component == 34)) {
                crate   = 79;
                slot    = 4;
                channel = 413;
        }
        else if ((sector == 1) && (layer == 21) && (component == 39)) {
                crate   = 79;
                slot    = 4;
                channel = 414;
        }
        else if ((sector == 1) && (layer == 11) && (component == 35)) {
                crate   = 79;
                slot    = 4;
                channel = 415;
        }
        else if ((sector == 1) && (layer == 11) && (component == 32)) {
                crate   = 79;
                slot    = 4;
                channel = 416;
        }
        else if ((sector == 1) && (layer == 51) && (component == 72)) {
                crate   = 79;
                slot    = 4;
                channel = 417;
        }
        else if ((sector == 1) && (layer == 51) && (component == 75)) {
                crate   = 79;
                slot    = 4;
                channel = 418;
        }
        else if ((sector == 1) && (layer == 51) && (component == 73)) {
                crate   = 79;
                slot    = 4;
                channel = 419;
        }
        else if ((sector == 1) && (layer == 51) && (component == 76)) {
                crate   = 79;
                slot    = 4;
                channel = 420;
        }
        else if ((sector == 1) && (layer == 51) && (component == 74)) {
                crate   = 79;
                slot    = 4;
                channel = 421;
        }
        else if ((sector == 1) && (layer == 42) && (component == 67)) {
                crate   = 79;
                slot    = 4;
                channel = 422;
        }
        else if ((sector == 1) && (layer == 42) && (component == 64)) {
                crate   = 79;
                slot    = 4;
                channel = 423;
        }
        else if ((sector == 1) && (layer == 42) && (component == 68)) {
                crate   = 79;
                slot    = 4;
                channel = 424;
        }
        else if ((sector == 1) && (layer == 42) && (component == 65)) {
                crate   = 79;
                slot    = 4;
                channel = 425;
        }
        else if ((sector == 1) && (layer == 41) && (component == 65)) {
                crate   = 79;
                slot    = 4;
                channel = 426;
        }
        else if ((sector == 1) && (layer == 42) && (component == 66)) {
                crate   = 79;
                slot    = 4;
                channel = 427;
        }
        else if ((sector == 1) && (layer == 41) && (component == 66)) {
                crate   = 79;
                slot    = 4;
                channel = 428;
        }
        else if ((sector == 1) && (layer == 41) && (component == 63)) {
                crate   = 79;
                slot    = 4;
                channel = 429;
        }
        else if ((sector == 1) && (layer == 41) && (component == 67)) {
                crate   = 79;
                slot    = 4;
                channel = 430;
        }
        else if ((sector == 1) && (layer == 41) && (component == 64)) {
                crate   = 79;
                slot    = 4;
                channel = 431;
        }
        else if ((sector == 1) && (layer == 32) && (component == 55)) {
                crate   = 79;
                slot    = 4;
                channel = 432;
        }
        else if ((sector == 1) && (layer == 32) && (component == 53)) {
                crate   = 79;
                slot    = 4;
                channel = 433;
        }
        else if ((sector == 1) && (layer == 32) && (component == 56)) {
                crate   = 79;
                slot    = 4;
                channel = 434;
        }
        else if ((sector == 1) && (layer == 32) && (component == 54)) {
                crate   = 79;
                slot    = 4;
                channel = 435;
        }
        else if ((sector == 1) && (layer == 31) && (component == 55)) {
                crate   = 79;
                slot    = 4;
                channel = 436;
        }
        else if ((sector == 1) && (layer == 31) && (component == 53)) {
                crate   = 79;
                slot    = 4;
                channel = 437;
        }
        else if ((sector == 1) && (layer == 31) && (component == 56)) {
                crate   = 79;
                slot    = 4;
                channel = 438;
        }
        else if ((sector == 1) && (layer == 31) && (component == 54)) {
                crate   = 79;
                slot    = 4;
                channel = 439;
        }
        else if ((sector == 1) && (layer == 22) && (component == 42)) {
                crate   = 79;
                slot    = 4;
                channel = 440;
        }
        else if ((sector == 1) && (layer == 22) && (component == 41)) {
                crate   = 79;
                slot    = 4;
                channel = 441;
        }
        else if ((sector == 1) && (layer == 22) && (component == 44)) {
                crate   = 79;
                slot    = 4;
                channel = 442;
        }
        else if ((sector == 1) && (layer == 22) && (component == 43)) {
                crate   = 79;
                slot    = 4;
                channel = 443;
        }
        else if ((sector == 1) && (layer == 21) && (component == 43)) {
                crate   = 79;
                slot    = 4;
                channel = 444;
        }
        else if ((sector == 1) && (layer == 21) && (component == 42)) {
                crate   = 79;
                slot    = 4;
                channel = 445;
        }
        else if ((sector == 1) && (layer == 21) && (component == 44)) {
                crate   = 79;
                slot    = 4;
                channel = 446;
        }
        else if ((sector == 1) && (layer == 11) && (component == 36)) {
                crate   = 79;
                slot    = 4;
                channel = 447;
        }
        else if ((sector == 1) && (layer == 11) && (component == 37)) {
                crate   = 79;
                slot    = 4;
                channel = 448;
        }
        else if ((sector == 1) && (layer == 51) && (component == 59)) {
                crate   = 79;
                slot    = 4;
                channel = 65;
        }
        else if ((sector == 1) && (layer == 51) && (component == 56)) {
                crate   = 79;
                slot    = 4;
                channel = 66;
        }
        else if ((sector == 1) && (layer == 51) && (component == 60)) {
                crate   = 79;
                slot    = 4;
                channel = 67;
        }
        else if ((sector == 1) && (layer == 51) && (component == 57)) {
                crate   = 79;
                slot    = 4;
                channel = 68;
        }
        else if ((sector == 1) && (layer == 42) && (component == 52)) {
                crate   = 79;
                slot    = 4;
                channel = 69;
        }
        else if ((sector == 1) && (layer == 51) && (component == 58)) {
                crate   = 79;
                slot    = 4;
                channel = 70;
        }
        else if ((sector == 1) && (layer == 42) && (component == 53)) {
                crate   = 79;
                slot    = 4;
                channel = 71;
        }
        else if ((sector == 1) && (layer == 42) && (component == 49)) {
                crate   = 79;
                slot    = 4;
                channel = 72;
        }
        else if ((sector == 1) && (layer == 41) && (component == 51)) {
                crate   = 79;
                slot    = 4;
                channel = 73;
        }
        else if ((sector == 1) && (layer == 42) && (component == 50)) {
                crate   = 79;
                slot    = 4;
                channel = 74;
        }
        else if ((sector == 1) && (layer == 41) && (component == 52)) {
                crate   = 79;
                slot    = 4;
                channel = 75;
        }
        else if ((sector == 1) && (layer == 42) && (component == 51)) {
                crate   = 79;
                slot    = 4;
                channel = 76;
        }
        else if ((sector == 1) && (layer == 41) && (component == 53)) {
                crate   = 79;
                slot    = 4;
                channel = 77;
        }
        else if ((sector == 1) && (layer == 41) && (component == 49)) {
                crate   = 79;
                slot    = 4;
                channel = 78;
        }
        else if ((sector == 1) && (layer == 32) && (component == 43)) {
                crate   = 79;
                slot    = 4;
                channel = 79;
        }
        else if ((sector == 1) && (layer == 41) && (component == 50)) {
                crate   = 79;
                slot    = 4;
                channel = 80;
        }
        else if ((sector == 1) && (layer == 32) && (component == 44)) {
                crate   = 79;
                slot    = 4;
                channel = 81;
        }
        else if ((sector == 1) && (layer == 32) && (component == 41)) {
                crate   = 79;
                slot    = 4;
                channel = 82;
        }
        else if ((sector == 1) && (layer == 31) && (component == 43)) {
                crate   = 79;
                slot    = 4;
                channel = 83;
        }
        else if ((sector == 1) && (layer == 32) && (component == 42)) {
                crate   = 79;
                slot    = 4;
                channel = 84;
        }
        else if ((sector == 1) && (layer == 31) && (component == 44)) {
                crate   = 79;
                slot    = 4;
                channel = 85;
        }
        else if ((sector == 1) && (layer == 31) && (component == 41)) {
                crate   = 79;
                slot    = 4;
                channel = 86;
        }
        else if ((sector == 1) && (layer == 22) && (component == 34)) {
                crate   = 79;
                slot    = 4;
                channel = 87;
        }
        else if ((sector == 1) && (layer == 31) && (component == 42)) {
                crate   = 79;
                slot    = 4;
                channel = 88;
        }
        else if ((sector == 1) && (layer == 21) && (component == 34)) {
                crate   = 79;
                slot    = 4;
                channel = 89;
        }
        else if ((sector == 1) && (layer == 22) && (component == 32)) {
                crate   = 79;
                slot    = 4;
                channel = 90;
        }
        else if ((sector == 1) && (layer == 21) && (component == 35)) {
                crate   = 79;
                slot    = 4;
                channel = 91;
        }
        else if ((sector == 1) && (layer == 22) && (component == 33)) {
                crate   = 79;
                slot    = 4;
                channel = 92;
        }
        else if ((sector == 1) && (layer == 11) && (component == 28)) {
                crate   = 79;
                slot    = 4;
                channel = 93;
        }
        else if ((sector == 1) && (layer == 21) && (component == 33)) {
                crate   = 79;
                slot    = 4;
                channel = 94;
        }
        else if ((sector == 1) && (layer == 11) && (component == 29)) {
                crate   = 79;
                slot    = 4;
                channel = 95;
        }
        else if ((sector == 1) && (layer == 11) && (component == 27)) {
                crate   = 79;
                slot    = 4;
                channel = 96;
        }
        else if ((sector == 1) && (layer == 51) && (component == 61)) {
                crate   = 79;
                slot    = 4;
                channel = 97;
        }
        else if ((sector == 1) && (layer == 51) && (component == 64)) {
                crate   = 79;
                slot    = 4;
                channel = 98;
        }
        else if ((sector == 1) && (layer == 51) && (component == 62)) {
                crate   = 79;
                slot    = 4;
                channel = 99;
        }
        else if ((sector == 1) && (layer == 51) && (component == 65)) {
                crate   = 79;
                slot    = 4;
                channel = 100;
        }
        else if ((sector == 1) && (layer == 51) && (component == 63)) {
                crate   = 79;
                slot    = 4;
                channel = 101;
        }
        else if ((sector == 1) && (layer == 51) && (component == 66)) {
                crate   = 79;
                slot    = 4;
                channel = 102;
        }
        else if ((sector == 1) && (layer == 42) && (component == 54)) {
                crate   = 79;
                slot    = 4;
                channel = 103;
        }
        else if ((sector == 1) && (layer == 42) && (component == 57)) {
                crate   = 79;
                slot    = 4;
                channel = 104;
        }
        else if ((sector == 1) && (layer == 42) && (component == 55)) {
                crate   = 79;
                slot    = 4;
                channel = 105;
        }
        else if ((sector == 1) && (layer == 42) && (component == 58)) {
                crate   = 79;
                slot    = 4;
                channel = 106;
        }
        else if ((sector == 1) && (layer == 42) && (component == 56)) {
                crate   = 79;
                slot    = 4;
                channel = 107;
        }
        else if ((sector == 1) && (layer == 41) && (component == 56)) {
                crate   = 79;
                slot    = 4;
                channel = 108;
        }
        else if ((sector == 1) && (layer == 41) && (component == 54)) {
                crate   = 79;
                slot    = 4;
                channel = 109;
        }
        else if ((sector == 1) && (layer == 41) && (component == 57)) {
                crate   = 79;
                slot    = 4;
                channel = 110;
        }
        else if ((sector == 1) && (layer == 41) && (component == 55)) {
                crate   = 79;
                slot    = 4;
                channel = 111;
        }
        else if ((sector == 1) && (layer == 41) && (component == 58)) {
                crate   = 79;
                slot    = 4;
                channel = 112;
        }
        else if ((sector == 1) && (layer == 32) && (component == 45)) {
                crate   = 79;
                slot    = 4;
                channel = 113;
        }
        else if ((sector == 1) && (layer == 32) && (component == 47)) {
                crate   = 79;
                slot    = 4;
                channel = 114;
        }
        else if ((sector == 1) && (layer == 32) && (component == 46)) {
                crate   = 79;
                slot    = 4;
                channel = 115;
        }
        else if ((sector == 1) && (layer == 32) && (component == 48)) {
                crate   = 79;
                slot    = 4;
                channel = 116;
        }
        else if ((sector == 1) && (layer == 31) && (component == 45)) {
                crate   = 79;
                slot    = 4;
                channel = 117;
        }
        else if ((sector == 1) && (layer == 31) && (component == 47)) {
                crate   = 79;
                slot    = 4;
                channel = 118;
        }
        else if ((sector == 1) && (layer == 31) && (component == 46)) {
                crate   = 79;
                slot    = 4;
                channel = 119;
        }
        else if ((sector == 1) && (layer == 31) && (component == 48)) {
                crate   = 79;
                slot    = 4;
                channel = 120;
        }
        else if ((sector == 1) && (layer == 22) && (component == 35)) {
                crate   = 79;
                slot    = 4;
                channel = 121;
        }
        else if ((sector == 1) && (layer == 22) && (component == 37)) {
                crate   = 79;
                slot    = 4;
                channel = 122;
        }
        else if ((sector == 1) && (layer == 22) && (component == 36)) {
                crate   = 79;
                slot    = 4;
                channel = 123;
        }
        else if ((sector == 1) && (layer == 21) && (component == 37)) {
                crate   = 79;
                slot    = 4;
                channel = 124;
        }
        else if ((sector == 1) && (layer == 21) && (component == 36)) {
                crate   = 79;
                slot    = 4;
                channel = 125;
        }
        else if ((sector == 1) && (layer == 21) && (component == 38)) {
                crate   = 79;
                slot    = 4;
                channel = 126;
        }
        else if ((sector == 1) && (layer == 11) && (component == 30)) {
                crate   = 79;
                slot    = 4;
                channel = 127;
        }
        else if ((sector == 1) && (layer == 11) && (component == 31)) {
                crate   = 79;
                slot    = 4;
                channel = 128;
        }
        else {
                crate   = -1;
                slot    = -1;
                channel = -1;
        }
}

